### ISSUE TITLE
Link on e-mail text

### ISSUE THREAD

**Issue by robciucioan** [catalinteodorescu/kyte#4]
Add link on e-mail text.

Example: <a href="mailto:contact@yourwebsite.com" title="E-mail">contact@yourwebsite.com</a>.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/8695094/6402225/a69e0dfa-be0e-11e4-91ba-766a2ab4c75a.png)

**Comment by robciucioan** [comment]
@catalinteodorescu, de ce ai închis issue? Nu văd commit-ul.

**Comment by catalinteodorescu** [comment]
nu stiu cum sa-l pun aici :(((
